baseURL = "/"
languageCode = "en-us"
title = "chronicpizza"
theme = "simple"

 [[menu.main]]
  name = "home"
  url  = "/"
  weight = 0

 [[menu.main]]
  name = "about me"
  url  = "/about"
  weight = 5

[params]
subtitle = "tech, nature, chronic pain"
favicon = "/images/favico.png"
referrer = "always"
author = "chronic pizza"
description = "pizza pizza"
