baseURL = "/"
languageCode = "en-us"
title = "chron·ic·piz·za"
theme = "simple"

[[menu.main]]
name = "home"
url  = "/"
weight = 0

[[menu.main]]
name = "about"
url  = "/about"
weight = 5

[[menu.main]]
name = "tags"
url  = "/tags"
weight = 3

[Author]
  name = "knoppers"


[params]
subtitle = "tech, nature, chronic pain"
favicon = "/images/favico.png"
referrer = "always"
description = "pizza pizza"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
